spring:
  web:
    cors:
      allowed-origins: "http://localhost:5000,http://127.0.0.1:5000"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Ne_D1vAn_n
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true